AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  EventsTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/api/lambda.handler
      Runtime: nodejs4.3
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          EVENTS_TABLE_NAME: !Ref EventsTable
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY
